const Aliya=[
{
    category:"toy",
    price:"200",
    img:"toy1.jpg",
    name:"min 70% off",
},
{
    category:"toy",
    price:200,
    img:"toy2.jpg",
    name:"min 70% off",
},
{
    category:"toy",
    price:200,
    img:"toy3.jpg",
    name:"min 70% off",
},
{
    category:"fashion",
    price:200,
    img:"pic1.jpg",
    name:"min 70% off",
},
{
    category:"fashion",
    price:200,
    img:"pic2.jpg",
    name:"min 70% off",
},
{
    category:"fashion",
    price:200,
    img:"pic3.jpg",
    name:"min 70% off",
},
{
    category:"fashion",
    price:200,
    img:"pic4.jpg",
    name:"min 70% off",
},
{
    category:"fashion",
    price:200,
    img:"pic5.jpg",
    name:"min 70% off",
},
{
    category:"fashion",
    price:200,
    img:"pic6.jpg",
    name:"min 70% off",
},
{
    category:"fashion",
    price:200,
    img:"pic7.jpg",
    name:"min 70% off",
},
{
    category:"electronics",
    price:200,
    img:"mob1.jpg",
    name:"min 70% off",
},
{
    category:"electronics",
    price:200,
    img:"mob2.jpg",
    name:"min 70% off",
},
{
    category:"electronics",
    price:200,
    img:"mob3.jpg",
    name:"min 70% off",
},
{
    category:"electronics",
    price:200,
    img:"mob4.jpg",
    name:"min 70% off",
},
{
    category:"home",
    price:200,
    img:"home1.jpg",
    name:"min 70% off",
},
{
    category:"home",
    price:200,
    img:"home2.jpg",
    name:"min 70% off",
},
{
    category:"home",
    price:200,
    img:"home3.jpg",
    name:"min 70% off",
},
{
    category:"grocery",
    price:200,
    img:"gross1.jpg",
    name:"min 70% off",
},
{
    category:"grocery",
    price:200,
    img:"gross2.jpg",
    name:"min 70% off",
},
{
    category:"grocery",
    price:200,
    img:"gross3.jpg",
    name:"min 70% off",
},
{
    category:"grocery",
    price:200,
    img:"gross4.jpg",
    name:"min 70% off",
},
{
    category:"furniture",
    price:200,
    img:"fur1.jpg",
    name:"min 70% off",
},
{
    category:"furniture",
    price:200,
    img:"fur2.jpg",
    name:"min 70% off",
},
{
    category:"furniture",
    price:200,
    img:"fur3.jpg",
    name:"min 70% off",
},
{
    category:"furniture",
    price:200,
    img:"fur4.jpg",
    name:"min 70% off",
},
{
    category:"furniture",
    price:200,
    img:"fur5.jpg",
    name:"min 70% off",
},
{
    category:"appliance",
    price:200,
    img:"appli.jpg",
    name:"min 70% off",
},
{
    category:"appliance",
    price:200,
    img:"appli1.jpg",
    name:"min 70% off",
},
];
export default Aliya;